### ISSUE TITLE
PlanScene에서 Texture가 로딩 순서 버그 수정

### ISSUE THREAD

**Issue by Redrock912** [urine-scientists/revive#34]
내용을 바꾸고 다시 저장하면 페이지가 자동 로드되면서 좌표값이 고쳐지는 것을 봐서
로딩 순서 버그일거라고 추정됨.

**Comment by Redrock912** [comment]
첫번째로 의심가는건 dorabutton = new PIXI.Texture.from ...

**Comment by horace-velmont** [comment]
머지 완료되어 이슈 종료합니다
