### ISSUE TITLE
web security 요소 제거

### ISSUE THREAD

**Issue by horace-velmont** [urine-scientists/revive#7]
- https://github.com/urine-scientists/revive/network/alert/package-lock.json/webpack-dev-server/open

package.json 수정하여 해당 security 문제 없도록 수정
만약 devDependencies로 수정할 것이라면 devDependencies의 역할이 무엇인지에 대해 조사

**Comment by Redrock912** [comment]
webpack-dev-server 버젼을 바꿀시에 다른 것들도 다 건드리기에 작업을 넘김.

**Comment by horace-velmont** [comment]
로직 이슈가 아닌 security 이슈여서 마스터 선반영 완료
