### ISSUE TITLE
Pixi 드래그 드롭 (+정보도 저장)

### ISSUE THREAD

**Issue by Redrock912** [urine-scientists/revive#9]
1. 드래그 드롭 시에 캐릭터 위치 이동.
2. 드래그 드롭 완료 시에 데이터 저장

**Comment by horace-velmont** [comment]
about sceneManager ? 
- https://github.com/gamestdio/pixi-engine

**Comment by horace-velmont** [comment]
정보저장은 각 씬에서 Game.getInstance().loadInfo("sceneName") 하기로 결정
